name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install
        run: npm install

      - name: Build (with base path)
        env:
          VITE_BASE: "/${{ github.event.repository.name }}/"
          VITE_EMAIL_SERVICE_ID: ${{ secrets.VITE_EMAIL_SERVICE_ID }}
          VITE_EMAIL_TEMPLATE_CONTACTUS_ID: ${{ secrets.VITE_EMAIL_TEMPLATE_CONTACTUS_ID }}
          VITE_EMAIL_TEMPLATE_RESERVE_ID: ${{ secrets.VITE_EMAIL_TEMPLATE_RESERVE_ID }}
          VITE_EMAIL_PUBLIC_KEY: ${{ secrets.VITE_EMAIL_PUBLIC_KEY }}
          VITE_PASSWORD: ${{ secrets.VITE_PASSWORD }}
        run: |
          VITE_BASE=$VITE_BASE npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
