name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Build (with base path)
        env:
          VITE_BASE: "/${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        run: |
          echo "export default { base: '$VITE_BASE' }" > vite.config.deploy.js
          mv vite.config.js vite.config.local.js
          mv vite.config.deploy.js vite.config.js

          npm run build

          mv vite.config.local.js vite.config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
